name: locator_sample
description: A Kosher Me app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^13.0.0
  persistent_bottom_nav_bar: ^4.0.2
  geolocator: ^9.0.2
  url_launcher: ^6.1.7
  lottie: ^2.1.0
  move_to_background: ^1.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.5
  firebase_core: ^2.12.0
  firebase_messaging: ^14.2.1
  bloc:
  flutter_bloc:
  dio:
  flutter_overlay_loader: ^2.0.0
  cached_network_image: ^3.2.3
  sizer: ^2.0.15
  flutter_svg: ^2.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  #   To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
